### ISSUE TITLE
Alignment of partners grid view 

### ISSUE THREAD

**Issue by devanshkh** [superpowerlabs/mobland-website#14]
- The grid looks like its aligned to the left
- We can squeeze in one more partner/investor on the right side
- this will align the rows instead of having a lone partner/investors on the last row

**Comment by sullof** [comment]
@devanshkh
The grid is dynamic. So, what you see in any row depends on the resolution. Try to change the width and you will see it.

**Comment by sullof** [comment]
We can make it fixed, but that would become a problem with some resolutions.

**Comment by devanshkh** [comment]
> We can make it fixed, but that would become a problem with some resolutions.

Sounds good - I have checked on multiple browsers, resolutions including mobile. The current layout is very buggy on mobile. Pls confirm is that's the case on your side too

**Comment by sullof** [comment]
@roquesrolando Can you try to fix it for mobile?

**Comment by jerrybassat7** [comment]
https://github.com/superpowerlabs/mobland-website/pull/18.
